---
openvpn_domain: "{{ inventory_hostname }}"
letsencrypt_email: admin@example.com
letsencrypt_staging: true

openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun
openvpn_service_name: openvpn-server@server
openvpn_network: 10.8.0.0
openvpn_netmask: 255.255.255.0
openvpn_cidr: 10.8.0.0/24
openvpn_dns_servers:
  - 1.1.1.1
  - 8.8.8.8
openvpn_push_routes: []
openvpn_keepalive: "10 120"
openvpn_cipher: AES-256-GCM
openvpn_auth_digest: SHA256
openvpn_tls_version_min: "1.2"
openvpn_status_log: /var/log/openvpn/status.log
openvpn_verb: 3
openvpn_packages:
  - openvpn
  - openvpn-auth-ldap
  - certbot
  - python3-certbot-dns-route53
  - iptables-persistent

openvpn_ca_path: "/etc/letsencrypt/live/{{ openvpn_domain }}/chain.pem"
openvpn_cert_path: "/etc/letsencrypt/live/{{ openvpn_domain }}/cert.pem"
openvpn_key_path: "/etc/letsencrypt/live/{{ openvpn_domain }}/privkey.pem"

openvpn_ldap_url: ldap://ldap.example.com
openvpn_ldap_plugin_path: /usr/lib/openvpn/openvpn-auth-ldap.so
openvpn_ldap_bind_dn: ""
openvpn_ldap_bind_password: ""
openvpn_ldap_base_dn: ou=users,dc=example,dc=com
openvpn_ldap_login_attribute: uid
openvpn_ldap_require_group: false
openvpn_ldap_group_base_dn: ou=groups,dc=example,dc=com
openvpn_ldap_group_search_filter: "(cn=vpn-users)"
openvpn_ldap_group_member_attribute: member
